# Generated by Django 5.2.8 on 2025-11-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("CODING", "Coding Agent"),
                            ("CODE_REVIEW", "Code Reviewer"),
                            ("DEVOPS", "DevOps Agent"),
                            ("QA", "QA Agent"),
                            ("BA", "Business Analyst"),
                            ("PM", "Project Manager"),
                            ("SCRUM_MASTER", "Scrum Master"),
                            ("RELEASE_MANAGER", "Release Manager"),
                            ("BUG_TRIAGE", "Bug Triage Agent"),
                            ("SECURITY", "Security Agent"),
                            ("PERFORMANCE", "Performance Agent"),
                            ("DOCUMENTATION", "Documentation Agent"),
                            ("UI_UX", "UI/UX Agent"),
                            ("DATA_ANALYST", "Data Analyst"),
                            ("SUPPORT", "Support Agent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                ("execution_time_seconds", models.FloatField(default=0.0)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("raw_request", models.JSONField(default=dict)),
                ("raw_response", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "agent_executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AgentTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("CODING", "Coding Agent"),
                            ("CODE_REVIEW", "Code Reviewer"),
                            ("DEVOPS", "DevOps Agent"),
                            ("QA", "QA Agent"),
                            ("BA", "Business Analyst"),
                            ("PM", "Project Manager"),
                            ("SCRUM_MASTER", "Scrum Master"),
                            ("RELEASE_MANAGER", "Release Manager"),
                            ("BUG_TRIAGE", "Bug Triage Agent"),
                            ("SECURITY", "Security Agent"),
                            ("PERFORMANCE", "Performance Agent"),
                            ("DOCUMENTATION", "Documentation Agent"),
                            ("UI_UX", "UI/UX Agent"),
                            ("DATA_ANALYST", "Data Analyst"),
                            ("SUPPORT", "Support Agent"),
                        ],
                        help_text="Type of agent to handle this task",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "input_data",
                    models.JSONField(
                        default=dict, help_text="Input parameters for the task"
                    ),
                ),
                (
                    "output_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Output result from the agent",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5, help_text="1-10, where 1 is highest priority"
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                ("execution_time_seconds", models.FloatField(default=0.0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "agent_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("OPENAI", "OpenAI"),
                            ("ANTHROPIC", "Anthropic"),
                            ("GOOGLE", "Google"),
                            ("OLLAMA", "Ollama"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=500)),
                ("api_url", models.URLField(blank=True)),
                ("model_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("max_tokens", models.IntegerField(default=4096)),
                ("temperature", models.FloatField(default=0.7)),
                (
                    "config",
                    models.JSONField(
                        default=dict, help_text="Additional configuration"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ai_providers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Prompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agent_type",
                    models.CharField(
                        choices=[
                            ("CODING", "Coding Agent"),
                            ("CODE_REVIEW", "Code Reviewer"),
                            ("DEVOPS", "DevOps Agent"),
                            ("QA", "QA Agent"),
                            ("BA", "Business Analyst"),
                            ("PM", "Project Manager"),
                            ("SCRUM_MASTER", "Scrum Master"),
                            ("RELEASE_MANAGER", "Release Manager"),
                            ("BUG_TRIAGE", "Bug Triage Agent"),
                            ("SECURITY", "Security Agent"),
                            ("PERFORMANCE", "Performance Agent"),
                            ("DOCUMENTATION", "Documentation Agent"),
                            ("UI_UX", "UI/UX Agent"),
                            ("DATA_ANALYST", "Data Analyst"),
                            ("SUPPORT", "Support Agent"),
                        ],
                        help_text="Agent type this prompt belongs to",
                        max_length=50,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Prompt identifier", max_length=100),
                ),
                (
                    "system_prompt",
                    models.TextField(help_text="System prompt for the agent"),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "prompts",
                "ordering": ["-created_at"],
            },
        ),
    ]
