# Generated by Django 5.2.8 on 2025-11-30 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agenttask",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Human user assigned to review/approve",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agenttask",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="agenttask",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="agents.agenttask",
            ),
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="executions",
                to="agents.agenttask",
            ),
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agents.aiprovider",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together={("agent_type", "name", "version")},
        ),
        migrations.AddField(
            model_name="agentexecution",
            name="prompt_used",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="agents.prompt",
            ),
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(
                fields=["agent_type", "status"], name="agent_tasks_agent_t_3b1bcd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(
                fields=["created_by", "status"], name="agent_tasks_created_a1ae55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="agenttask",
            index=models.Index(
                fields=["priority", "created_at"], name="agent_tasks_priorit_84790f_idx"
            ),
        ),
    ]
